### ISSUE TITLE
List of planets is alphabetized by the C# code, despite TSV being in distance from sun order. (ungroups planets)

### ISSUE THREAD

**Issue by Cyber-Shark** [bucketon/OWRandomSpeedrun#125]

**Comment by bucketon** [comment]
at first I thought this might be Linq scrambling the lists, but we aren't actually using Linq on the menu lists, just the lists for random spawn and goal from the pause menu

**Comment by cmaines** [comment]
This was broken by https://github.com/bucketon/OWRandomSpeedrun/commit/601bae55123aa56fb6ac59e30f1e56bbcb3d00a2. That commit also erroneously deleted some other changes.
