### ISSUE TITLE
Create an image for the mod and add it to the README

### ISSUE THREAD

**Issue by cmaines** [bucketon/OWRandomSpeedrun#129]
The [instructions for publishing a mod](https://owml.outerwildsmods.com/guides/publishing.html) say the following:
> The first image in your README file will be used as the mod's thumbnail on the website, to insert an image, simply paste it inside of the editor. Make sure it's at the very top of your document.

We should create an image for the mod and insert it in our README.

**Comment by bucketon** [comment]
I added an image, waiting for folks feedback before I mark this done

**Comment by bucketon** [comment]
fixed kerning issue folks pointed out, closing
