### ISSUE TITLE
Handle edge case(s) for lack of save file

### ISSUE THREAD

**Issue by cmaines** [bucketon/OWRandomSpeedrun#16]
As this gets built, multiple things could potentially break if somebody tries to use the mod without ever creating a save file.

We should first decide what should happen if somebody attempts to start the mod when they have never played the game, or if they've never gone beyond a single loop. We could potentially not show the mod menu items at all, show them an error if they try to do it, or make it actually work (if it doesn't already).

**Comment by bucketon** [comment]
https://github.com/bucketon/OWRandomSpeedrun/pull/48
