### ISSUE TITLE
After warping, change the player's orientation to face the goal

### ISSUE THREAD

**Issue by cmaines** [bucketon/OWRandomSpeedrun#35]
Per David, sometimes when you spawn, you can't see the goal on the screen because you are not facing it. We could change the player's orientation after warping so that the goal is at the center of the screen.

An alternative would be to persistently show the goal on the HUD; David likes that idea, personally I think changing orientation is sufficient.

**Comment by bucketon** [comment]
it technically is persistently shown, it just might be hidden in the corner of the helmet?
