### ISSUE TITLE
Only disable timber hearth village music if the player spawns outside timber hearth

### ISSUE THREAD

**Issue by bkirz** [bucketon/OWRandomSpeedrun#40]
This code disables timber hearth music when the player awakens, which is needed to prevent it from playing if the player spawns in a non-timber hearth location: https://github.com/bucketon/OWRandomSpeedrun/blob/b73478e93d7da684b4ee085cf07e030bbb4e0cc5/OuterWildsRandomSpeedrun/OuterWildsRandomSpeedrun.cs#L145-L146

As currently written, this logic always runs, even if the player spawns on timber hearth. Once our list of spawn points is struct-ified, we should extend that struct with a field to determine if the player spawns on timber hearth or not. Then we can modify this code to conditionally disable music based on that flag.

**Comment by bucketon** [comment]
https://github.com/bucketon/OWRandomSpeedrun/pull/91
