### ISSUE TITLE
Store the list of spawn points as structs

### ISSUE THREAD

**Issue by bkirz** [bucketon/OWRandomSpeedrun#41]
Once #36 is merged, extend the list into a list of structs. This will let us associate additional data with each spawn point, including:
- a human-readable name for the spawn point
- additional information that may influence mod behavior, such as whether or not the spawn point is on timber hearth for #40.

**Comment by bucketon** [comment]
the timber hearth bool should be specifically if it's in the village, the music is triggered by a big volume that covers the whole area, but not the whole planet.

**Comment by bucketon** [comment]
fields I am aware of that we currently need:
isTimberHearthVillage
doNotSpawn
doNotGoal
prettyName

**Comment by bkirz** [comment]
I'm thinking we only really need to encode the following as fields:
- the spawn point's canonical name
- a pretty version to render in menus/etc
- metadata that we could then use to determine programmatically whether the location should be used as a spawn point or goal.

Then, we can incorporate that metadata into methods that enumerate a list of possible spawn points. For example, we know we likely won't want to spawn the player at any dream world spawn point; easiest to mark those spawn points all as dream world spawns and then check that flag in one place later so we can more easily change that logic in the future without having to manually change the dreamworld spawns.

Will sketch this out today.

**Comment by cmaines** [comment]
@bucketon added support for the other struct fields in https://github.com/bucketon/OWRandomSpeedrun/commit/f90162bd54d7f075ad4dc03b2cf0d69421e6a750. Is this good to close?
