### ISSUE TITLE
upon using the reset spawn and goal menu item, the clock disappears

### ISSUE THREAD

**Issue by bucketon** [bucketon/OWRandomSpeedrun#66]

**Comment by cmaines** [comment]
Observed behavior:
- If you use the 'randomize spawn and goal' button without having completed a speedrun, the timer does not disappear, but it restarts from the time that you click the button, and not once the player has the ability to wake up
- If you complete a speedrun and the timer is stopped, both using the 'randomize spawn and goal' button or quitting to the title screen and starting a new run causes the timer to not appear.
