### ISSUE TITLE
Spawning sometimes still immediately results in death

### ISSUE THREAD

**Issue by cmaines** [bucketon/OWRandomSpeedrun#68]
Happened a few times, including for the Southern Observatory spawn.

**Comment by cmaines** [comment]
Maybe related to #69? Not sure.

**Comment by bucketon** [comment]
duplicate of https://github.com/bucketon/OWRandomSpeedrun/issues/69 as far as I can tell

**Comment by bucketon** [comment]
oh oops my log was causing an identical NRE, reopening
